import Head from 'next/head'
import { useWeb3React } from '@web3-react/core'
import { injected } from '../components/wallet/connector'
import styles from '../styles/Home.module.css'

export default function Home() {
  const {active, account, library, connector, activate, deactivate} = useWeb3React()
  const connect = async() => {
    try {
      await activate(injected)
    } catch (error) {
      console.log(error)
    }
  }

  const disconnect = async() => {
    try {
      await deactivate()
    } catch (error) {
      console.log(error)
    }
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
      <button type="button" className="..." onClick={connect}>
        Connect to metamask
      </button>
      {
        active &&
        <div>
        <h3>{`Connected  with: ${account}`}</h3>
        <button type="button" className="..." onClick={disconnect}>
        Disconnect from metamask
      </button>
        </div>
      }
      {
        !active &&
        <h3>Not connected</h3>
      }
      </div>

      
    </div>
  )
}
